### ISSUE TITLE
Attempt to Purchase error Cannot GET /window.location

### ISSUE THREAD

**Issue by jimboca** [UniversalDevicesInc/pg3#46]
First attempt to Purchase the WeatherFlow NS, clicked purchase, logged into Portal, and then got this error.

`Cannot GET /window.location?successful=false&error=System%20error%3A%20pid%20is%20not%20valid`

Also, I am already logged into the Portal inside PG3, why do I have to login again when I click purchase?

**Comment by bpaauwe** [comment]
I don't think this is a PG3 problem.  The purchasing system will only allow purchases from a registered Polisy and I believe that error is indicating that your Polisy is not registered.

I thought it was supposed to auto-register the first time you tried to purchase something.  I'll forward this on to Michel & Benoit

**Comment by BenoitMercier** [comment]
> I don't think this is a PG3 problem. The purchasing system will only allow purchases from a registered Polisy and I believe that error is indicating that your Polisy is not registered.

There us actually 2 issues.

1. The error "pid is not valid" does not refer to a registration. It means the pid format is not valid. It has to start with 00:21:b9 or 00:0d:b9. Here's the regex that the pid has to match: /^(?:uuid:)?(?=00:*21:*b9|00:*0d:*b9)([a-f\d]{2}):*([a-f\d]{2}):*([a-f\d]{2}):*([a-f\d]{2}):*([a-f\d]{2}):*([a-f\d]{2})$/i

2. The redirect url is wrong. It looks like the redirect url passed to /nodeserver/purchase is "window.location", whereas the intent must be the value of window.location.

**Comment by bpaauwe** [comment]
I just fixed the second issue, that will be in the next PG3 release.   However, with this fixed, I don't think the user is going to see any error messages.  I don't think PG3 has the ability to parse any query params nor am I familiar with how to make Angular do that.

PG3 is getting the mac address of the Polisy and sending that.  

I wonder if this is related to the other issue.  The mac address is now stored in the PG3 database but if you're still using an older version of the database without that field, it may not be getting set.

**Comment by jimboca** [comment]
Deleting and reinstalling PG3 has made this better, but there is still an issue.
I had my development ISY selected on the PG3 dashboard which is 00:21:b9:02:4a:56
Then I hit purchase for WeatherFlow which now allowed me to login, but it said the purchase was being selected for the ISY inside the Polisy which was not registered in the Portal, and asked if I wanted to register it.  I said yes, but then realized the payment would be tied to that ISY instead of my dev, so I canceled it, then I got this same redirect error:
Cannot GET /window.location?successful=false&error=Cancelled

**Comment by bpaauwe** [comment]
Purchases are supposed to be tied to the Polisy, not the ISY.  The UUID 00:0d:b9 looks like a Polisy UUID so I think that's correct.  I'm not sure why it cares what the ISY ID is.

I fixed the re-direct in the code, but I'll need to make a release and it will need to get packaged before it will be available on the Polisy.

**Comment by jimboca** [comment]
OK, it makes sense that it's tied to the machine running Polyglot.  But was confusing that it shows the UUID of the ISY in the initial popup.  I guess I can go forward with the purchase :)

**Comment by mkohanim** [comment]
00:21:b9:02:4a:56 is an ISY MAC. You need to use Polisy MAC which starts with 00:0d:b9.

With kind regards,

******************************
  Michel Kohanim
             CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by bpaauwe** [comment]
Fixed in version 3.0.20
